### ISSUE TITLE
Do permission review

### ISSUE THREAD

**Issue by yanniboi** [yanniboi/simplytest#14]
Lets decide on a list of permissions that we need for front end users and admin for the site.

It might be as simple as admins can do everything ('administer simplytest') and anyone can create submissions (no permission needed).

**Comment by patrickd-** [comment]
One usecase for a create-submission permission I can think of is the fact that I got mutliple requests over the years of people asking if they could setup their own private simplytest.me for their own projects (which with the new backend would actually be possible)

**Comment by yanniboi** [comment]
Cool sounds good to me!

**Comment by yanniboi** [comment]
This is now being handled by:
https://github.com/yanniboi/simplytest/issues/15
