### ISSUE TITLE
Create a theme for the profile

### ISSUE THREAD

**Issue by yanniboi** [yanniboi/simplytest#16]
Create a theme for simplytest.

**Comment by patrickd-** [comment]
When I started working on the 8.x-2.x port a while ago I think I created a subtheme based on bartik with some simplytest.me style changes. I don't remember the quality of it and if it would even be compatible with the current d8 core but it might help.

**Comment by yanniboi** [comment]
Great! I'll take a look :smile:

**Comment by yanniboi** [comment]
simplytesty - lol!

**Comment by yanniboi** [comment]
This is being handled by:
https://github.com/yanniboi/simplytest/pull/24
