### ISSUE TITLE
Disable form if no token configured

### ISSUE THREAD

**Issue by yanniboi** [yanniboi/simplytest#8]
I'm able to try launching sandboxes although spawn.sh token hasn't been set (progress page is shown with websocket errors in console, watchdog logs: No settings found for simplytest_submission)

**Comment by yanniboi** [comment]
Shall we print an error and not render form elements if the token has not been set?

**Comment by patrickd-** [comment]
Yeah I think disabling the add-submission form and showing an error status message should be fine. The status message should later link to a configuration page where it can be set without drush and if things get really fancy we could also add it to the drupal status report page but that's probably overkill for now.

**Comment by yanniboi** [comment]
This is being solved by #30
