### ISSUE TITLE
Combine status and view routes.

### ISSUE THREAD

**Issue by yanniboi** [yanniboi/simplytest#9]
submission/x is empty and should probably be submission/x/status?

**Comment by yanniboi** [comment]
Lets have one page to view submission information. We can add the collapsed log details (spawn log and build script) as well as see all the field information. This page should be behind an administer permission so that it remains private (see https://github.com/yanniboi/simplytest/issues/14).

I think it should have the admin theme and route as well, /admin/submission/{id}.

Lets display all fields for now, we can remove unnecessary detail later.

**Comment by patrickd-** [comment]
Yup, sounds good to me! :)

**Comment by yanniboi** [comment]
This is now being handled by:
https://github.com/yanniboi/simplytest/pull/6
